import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
const clubs=[["Aberdeen","Scotland",64,800],["Hearts","Scotland",65,900],["Hibernian","Scotland",63,750],["Celtic","Scotland",76,2800],["Rangers","Scotland",75,2700],["Sunderland","England",69,1800],["Leeds United","England",73,2500],["Newcastle","England",79,4500],["Liverpool","England",86,9500],["Manchester United","England",83,8000],["Arsenal","England",85,9000],["Brighton","England",74,3000],["Aston Villa","England",77,3400],["Athletic Club","Spain",77,3600],["Barcelona","Spain",88,11000],["Real Madrid","Spain",90,12500],["Bayern Munich","Germany",89,12000],["Dortmund","Germany",82,6000],["Inter","Italy",84,6500],["AC Milan","Italy",82,6000],["Juventus","Italy",83,6200],["Napoli","Italy",81,5200]];
const people=[["Emma","Partner"],["Ryan","Best friend"],["Mum","Family"],["Coach","Mentor"]];
const items=[["Mercurial Boots","👟",1200,"skill",3],["New Phone","📱",900,"morale",4],["Gaming PC","🖥️",1800,"morale",7],["Designer Watch","⌚",6500,"rep",3],["Sports Car","🏎️",45000,"rep",8],["Holiday","✈️",5000,"morale",18],["Gym Membership","🏋️",800,"skill",4],["Designer Clothes","🧥",2200,"rep",5],["PS5","🎮",500,"morale",3]];
const initial={name:"McIntee",age:16,club:"Aberdeen",position:"ST",foot:"Right",ovr:64,skill:48,fitness:82,morale:75,rep:18,apps:0,goals:0,assists:0,value:120000,money:4200,weekly:0,day:1,season:1,relationship:35,items:[],history:[]};
const positions=["ST","LW","RW","CAM","CM","CDM","LB","RB","CB","GK"];
const nationalities=["Scottish","English","Irish","Welsh","French","Spanish","German","Italian","Dutch","Portuguese"];
const backgrounds=[
["Academy standout","You were one of the most exciting players in the academy. Coaches expect you to make an impact early.",2,5],
["Late bloomer","You were overlooked for years, but a brilliant final academy season earned you a professional chance.",1,8],
["Local prospect","You grew up supporting the club and worked your way through the local youth setup.",1,4],
["International youth","You have already represented your country at youth level and arrive with a little extra attention.",3,6]
];
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)); const cash=n=>"£"+Math.round(n).toLocaleString("en-GB");
function load(){try{const r=localStorage.getItem("footballCareer");return r?{...initial,...JSON.parse(r)}:{...initial}}catch{return{...initial}}}
const Bar=({label,value})=><div className="barrow"><span>{label}</span><div className="bar"><i style={{width:clamp(value)+"%"}}/></div><b>{Math.round(value)}</b></div>;
function App(){
const[s,setS]=useState(load),[tab,setTab]=useState("career"),[screen,setScreen]=useState(()=>localStorage.getItem("footballCareer")?"landing":"creator");
const [form,setForm]=useState({first:"Scott",surname:"McIntee",age:16,nationality:"Scottish",position:"ST",foot:"Right",club:"Aberdeen"});
const [background,setBackground]=useState(0);
useEffect(()=>localStorage.setItem("footballCareer",JSON.stringify(s)),[s]);
function createPlayer(){
 const bg=backgrounds[background], c=clubs.find(x=>x[0]===form.club)||clubs[0];
 const ovr=(form.position==="GK"?62:64)+Math.floor(Math.random()*5);
 const player={...initial,name:((form.first||"Player")+" "+(form.surname||"")).trim(),age:Number(form.age),nationality:form.nationality,club:c[0],position:form.position,foot:form.foot,ovr,skill:48+bg[2],rep:18+bg[3],value:100000+ovr*1000,money:2500,weekly:0,day:1,season:1,relationship:35,apps:0,goals:0,assists:0,items:[],history:["Started at "+c[0]+" as a "+form.position+".",bg[0]+": "+bg[1]]};
 setS(player);localStorage.setItem("footballCareer",JSON.stringify(player));setScreen("game");setTab("career");
}
function editPlayer(){
 setForm({first:s.name?.split(" ")[0]||"Player",surname:s.name?.split(" ").slice(1).join(" ")||"",age:s.age,nationality:s.nationality||"Scottish",position:s.position,foot:s.foot,club:s.club});
 setScreen("creator");
}

function match(type){setS(p=>{const chance=clamp((p.ovr+p.skill+p.morale)/3+(type===2?5:0),5,95);const ok=Math.random()*100<chance;let n={...p,apps:p.apps+1,fitness:clamp(p.fitness-8),day:p.day+1};if(ok){const g=Math.random()<.34?1:0;const a=!g&&Math.random()<.35?1:0;n.goals+=g;n.assists+=a;n.rep=clamp(n.rep+(type===2?4:type===3?3:2));n.skill=clamp(n.skill+2);n.morale=clamp(n.morale+5);n.value+=35000;n.money+=n.weekly;n.history=[...n.history,["Match "+n.apps+": "+(g?"⚽ Scored!":a?"🎯 Assist!":"⭐ Solid performance.")+" — "+p.club]].flat().slice(-20)}else{n.rep=clamp(n.rep-1);n.morale=clamp(n.morale-6);n.history=[...n.history,"Match "+n.apps+": difficult outing — "+p.club].slice(-20)}if(n.apps===3&&!n.weekly){n.weekly=850;n.history=[...n.history,"Signed first professional contract: £850/week."].slice(-20)}if(n.day%30===0){n.age+=1;n.season+=1;n.ovr=clamp(n.ovr+Math.max(1,Math.round(n.skill/45)),40,95);n.history=[...n.history,"Birthday and new season: now "+n.age+"."].slice(-20)}return n})}
function buy(i){const x=items[i];if(s.money<x[2]||s.items.includes(x[0]))return;setS(p=>{const n={...p,money:p.money-x[2],items:[...p.items,x[0]],history:[...p.history,"Bought "+x[0]+"."].slice(-20)};n[x[3]]=clamp(n[x[3]]+x[4]);return n})}
function transfer(i){const c=clubs[i];if(s.ovr+8<c[2])return;setS(p=>({...p,club:c[0],weekly:c[3],money:p.money+c[3]*4,rep:clamp(p.rep+3),history:[...p.history,"Transferred to "+c[0]+" — "+cash(c[3])+"/week."].slice(-20)}))}
function spend(i){setS(p=>({...p,money:Math.max(0,p.money-100),relationship:i===0?clamp(p.relationship+8):p.relationship,morale:clamp(p.morale+4),history:[...p.history,"Spent time with "+people[i][0]+"."].slice(-20)}))}
function action(k){setS(p=>k==="rest"?{...p,fitness:clamp(p.fitness+18),morale:clamp(p.morale+5),day:p.day+1}:k==="train"?{...p,fitness:clamp(p.fitness-15),skill:clamp(p.skill+4),day:p.day+1}:{...p,money:Math.max(0,p.money-150),morale:clamp(p.morale+12),fitness:clamp(p.fitness-8),day:p.day+1})}
function home(name,cost){if(s.money<cost||s.items.includes(name))return;setS(p=>({...p,money:p.money-cost,items:[...p.items,name],morale:clamp(p.morale+8),history:[...p.history,"Moved into a "+name+"."].slice(-20)}))}
function reset(){if(confirm("Start a new career?")){localStorage.removeItem("footballCareer");setS({...initial});setScreen("creator");setTab("career")}}
if(screen==="landing")return <div className="landing"><div className="landingInner"><div className="brand">FOOTBALL <span>CAREER</span></div><div className="landingHero"><p className="creatorKicker">YOUR FOOTBALL STORY</p><h1>Build a career.<br/><em>Live the life.</em></h1><p>Create your player, choose your starting point and play through a full football career — matches, transfers, money, relationships and everything in between.</p><div className="landingButtons"><button className="startBtn" onClick={()=>{setForm({first:"Scott",surname:"McIntee",age:16,nationality:"Scottish",position:"ST",foot:"Right",club:"Aberdeen"});setScreen("creator")}}>Create new player →</button><button className="continueBtn" onClick={()=>setScreen("game")}>Continue career</button></div></div><div className="landingFeatures"><span>⚽ MATCHES</span><span>💷 MONEY</span><span>🔁 TRANSFERS</span><span>❤️ RELATIONSHIPS</span><span>🏠 LIFE</span></div></div></div>;
if(screen==="creator")return <div className="creator"><div className="creatorCard"><div className="brand">FOOTBALL <span>CAREER</span></div><p className="creatorKicker">PLAYER CREATOR</p><h1>Create your player.</h1><p className="muted">This is your story. Change anything before you start.</p><div className="formGrid"><label>First name<input value={form.first} onChange={e=>setForm({...form,first:e.target.value})}/></label><label>Surname<input value={form.surname} onChange={e=>setForm({...form,surname:e.target.value})}/></label><label>Age<select value={form.age} onChange={e=>setForm({...form,age:e.target.value})}><option>16</option><option>17</option><option>18</option></select></label><label>Nationality<select value={form.nationality} onChange={e=>setForm({...form,nationality:e.target.value})}>{nationalities.map(x=><option key={x}>{x}</option>)}</select></label><label>Position<select value={form.position} onChange={e=>setForm({...form,position:e.target.value})}>{positions.map(x=><option key={x}>{x}</option>)}</select></label><label>Preferred foot<select value={form.foot} onChange={e=>setForm({...form,foot:e.target.value})}><option>Right</option><option>Left</option></select></label><label className="wide">Starting club<select value={form.club} onChange={e=>setForm({...form,club:e.target.value})}>{clubs.filter(x=>x[2]<=70).map(x=><option key={x[0]}>{x[0]}</option>)}</select></label></div><div className="backgrounds"><h3>Starting background</h3>{backgrounds.map((x,i)=><button type="button" className={background===i?"backgroundPick selected":"backgroundPick"} onClick={()=>setBackground(i)} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></button>)}</div><div className="preview"><div><small>PLAYER</small><b>{form.first||"Player"} {form.surname}</b></div><div><small>POSITION</small><b>{form.position}</b></div><div><small>CLUB</small><b>{form.club}</b></div></div><div className="creatorActions"><button onClick={()=>setScreen(localStorage.getItem("footballCareer")?"landing":"creator")}>Back</button><button className="startBtn" onClick={createPlayer}>Save & start career →</button></div></div></div>;
const nav=[["career","Career"],["life","Life"],["relationships","Relationships"],["shop","Shop"],["clubs","Clubs"],["profile","Profile"]];
return <div className="app"><header><div className="brand">FOOTBALL <span>CAREER</span></div><div className="headerBtns"><button onClick={()=>setScreen("landing")}>Home</button><button onClick={editPlayer}>Edit player</button><button onClick={reset}>New career</button></div></header>
<section className="dashboard"><div className="card player"><div className="ovr">{s.ovr}<small>OVR</small></div><div><h1>{s.name}</h1><p>{s.club} · {s.position} · {s.foot}</p><div className="chips"><span>AGE {s.age}</span><span>{s.weekly?"PRO CONTRACT":"ACADEMY"}</span></div></div></div>
<div className="card stats">{[["APPS",s.apps],["GOALS",s.goals],["ASSISTS",s.assists],["VALUE",s.value>=1000000?"£"+(s.value/1000000).toFixed(1)+"m":cash(s.value)],["REP",s.rep]].map(x=><div className="stat" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div>
<div className="card money"><span>BANK</span><b>{cash(s.money)}</b><small>{cash(s.weekly)} / week</small></div></section>
<nav>{nav.map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><main>
tab==="career"&&<div className="grid2"><section className="card story"><div className="hero"><small>MATCHDAY {s.apps+1}</small><h2>{s.apps<2?"YOUR DEBUT":s.morale<45?"A DIFFICULT WEEK":"BREAKING THROUGH"}</h2><p>{s.apps<2?"Two forwards are out. The manager points at you in the tunnel. Your chance has arrived.":"You have a chance to make an impact. Your next decision could change your standing in the squad."}</p></div>{[["Do exactly that","Play exactly as instructed.","70%",1],["Play your way","Take risks and try to stand out.","40%",2],["Ask the captain","Get advice before going on.","60%",3]].map(x=><div className="choice" key={x[0]}><div><b>{x[0]}</b><p>{x[1]}</p></div><button onClick={()=>match(x[3])}>{x[2]} →</button></div>)}</section><section className="card side"><h2>Player condition</h2><p className="muted">Season {s.season} · Day {s.day}</p><Bar label="Fitness" value={s.fitness}/><Bar label="Morale" value={s.morale}/><Bar label="Skill" value={s.skill}/><Bar label="Reputation" value={s.rep}/><h2 className="sectionTitle">Recent history</h2>{s.history.slice(-6).reverse().map((x,i)=><div className="log" key={i}>{x}</div>)}</section></div>
tab==="life"&&<div className="grid2"><section className="card"><h2>Your Life</h2><p className="muted">The football career is only part of your life.</p><div className="cards">{[["Shared Flat","Basic accommodation",0],["City Apartment","Your first proper home",25000],["Luxury Apartment","A serious upgrade",120000],["Mansion","You made it",650000]].map(x=><div className="mini" key={x[0]}><h3>🏠 {x[0]}</h3><p>{x[1]}</p><strong>{x[2]?cash(x[2]):"Free"}</strong><button disabled={s.items.includes(x[0])} onClick={()=>home(x[0],x[2])}>{s.items.includes(x[0])?"Owned":"Move in"}</button></div>)}</div></section><section className="card"><h2>Daily choices</h2><p className="muted">Trade time, fitness, morale and money.</p><div className="actions"><button onClick={()=>action("rest")}>🛌 Rest & recover</button><button onClick={()=>action("train")}>🏋 Extra training</button><button onClick={()=>action("night")}>🍻 Night out</button></div></section></div>
tab==="relationships"&&<div className="grid2"><section className="card"><h2>Relationships</h2><p className="muted">People remember how you treat them.</p><div className="cards">{people.map((p,i)=>{const v=i===0?s.relationship:[58,72,64][i-1];return <div className="mini" key={p[0]}><h3>{i===0?"❤️":"👤"} {p[0]}</h3><p>{p[1]}</p><Bar label="Bond" value={v}/><button onClick={()=>spend(i)}>Spend time</button></div>})}</div></section><section className="card"><h2>Relationship system</h2><p className="muted">Relationships influence morale and can unlock story events.</p><div className="bond">{s.relationship}<small>/100 with Emma</small></div></section></div>
tab==="shop"&&<section className="card"><h2>Shop</h2><p className="muted">Use your football money to shape your lifestyle.</p><div className="cards">{items.map((x,i)=><div className="mini" key={x[0]}><div className="emoji">{x[1]}</div><h3>{x[0]}</h3><strong>{cash(x[2])}</strong><p>+{x[4]} {x[3]}</p><button disabled={s.items.includes(x[0])} onClick={()=>buy(i)}>{s.items.includes(x[0])?"Owned":"Buy"}</button></div>)}</div></section>
tab==="clubs"&&<section className="card"><h2>Club Market</h2><p className="muted">Clubs unlock as your player improves.</p><div className="cards">{clubs.filter(c=>c[2]<=s.ovr+8).map(c=><div className="mini" key={c[0]}><h3>{c[0]}</h3><p>{c[1]} · OVR {c[2]}</p><p>Weekly salary: {cash(c[3])}</p><button disabled={c[0]===s.club} onClick={()=>transfer(clubs.indexOf(c))}>{c[0]===s.club?"Current club":"Transfer"}</button></div>)}</div></section>
tab==="profile"&&<div className="grid2"><section className="card"><h2>Player Profile</h2><Bar label="OVR" value={s.ovr}/><Bar label="Skill" value={s.skill}/><Bar label="Fitness" value={s.fitness}/><Bar label="Morale" value={s.morale}/><Bar label="Reputation" value={s.rep}/><hr/><dl><div><dt>Age</dt><dd>{s.age}</dd></div><div><dt>Club</dt><dd>{s.club}</dd></div><div><dt>Position</dt><dd>{s.position}</dd></div><div><dt>Career earnings</dt><dd>{cash(s.money)}</dd></div></dl></section><section className="card"><h2>Career History</h2>{s.history.map((x,i)=><div className="log" key={i}>{x}</div>)}</section></div>
</main></div>}
createRoot(document.getElementById("root")).render(<App/>);